 const WHITELIST_CONTRACT_ADDRESS = "0x7f5937767D85E1EcCC43bAb44BCaf8f9E9EBBF93";
 // URL to extract Metadata for a Crypto Dev NFT
const METADATA_URL = "";

module.exports = { WHITELIST_CONTRACT_ADDRESS, METADATA_URL };